import { buildCanonicalToolRegistry, type CanonicalToolSources } from './canonical-tool-registry.js';
import {
  audioTools,
  autoDreamTools,
  callbackMemoryTools,
  callbackTools,
  capabilityEvolutionChangeTools,
  capabilityEvolutionRoundTools,
  capabilityEvolutionTools,
  communityRouteAcceptanceTools,
  distillationTools,
  entrustedWorkReadTools,
  evalLifecycleTools,
  eventMemoryTools,
  evidenceTools,
  externalReviewVerdictTools,
  externalRuntimeSessionCallbackTools,
  externalRuntimeSessionReadTools,
  fileSliceTools,
  financeTools,
  gameActionTools,
  graphTools,
  hubActionTools,
  libraryLifecycleTools,
  limbTools,
  listObjectivesTools,
  meetingArtifactTools,
  pawFeelDispositionTools,
  perspectiveTools,
  publishVerdictTools,
  recentTools,
  reportHarnessSignalTools,
  richBlockRulesTools,
  scheduleTools,
  sessionChainTools,
  shellTools,
  signalStudyTools,
  signalsTools,
  skillConsumptionTools,
  unitEvaluationTools,
} from './tools/index.js';

export const CANONICAL_TOOL_SOURCES = {
  collab: [
    ...callbackTools,
    ...capabilityEvolutionTools,
    ...capabilityEvolutionRoundTools,
    ...capabilityEvolutionChangeTools,
    ...autoDreamTools,
    ...communityRouteAcceptanceTools,
    ...externalReviewVerdictTools,
    ...externalRuntimeSessionCallbackTools,
    ...hubActionTools,
    ...skillConsumptionTools,
    ...entrustedWorkReadTools,
    ...eventMemoryTools,
    ...publishVerdictTools,
    ...evalLifecycleTools,
    ...pawFeelDispositionTools,
    ...richBlockRulesTools,
    ...gameActionTools,
    ...scheduleTools,
    ...shellTools,
    ...unitEvaluationTools,
    ...listObjectivesTools,
    ...reportHarnessSignalTools,
  ],
  memory: [
    ...callbackMemoryTools,
    ...distillationTools,
    ...evidenceTools,
    ...externalRuntimeSessionReadTools,
    ...meetingArtifactTools,
    ...fileSliceTools,
    ...graphTools,
    ...libraryLifecycleTools,
    ...perspectiveTools,
    ...recentTools,
    ...sessionChainTools,
  ],
  signals: [...signalsTools, ...signalStudyTools],
  limb: [...limbTools],
  audio: [...audioTools],
  finance: [...financeTools],
} as const satisfies CanonicalToolSources;

/** The only executable catalog. Every other server/profile view is derived from this registry. */
export const CANONICAL_TOOL_REGISTRY = buildCanonicalToolRegistry(CANONICAL_TOOL_SOURCES);
