/** F290 public participation uses an ephemeral exec session with no native private surface.
 * Config contract: https://developers.openai.com/codex/config-reference/ .
 * The installed CLI request/tool surface is also checked by the native policy probe.
 */
export const COLLECTIVE_CODEX_POLICY_ARGS = [
  '--ignore-user-config',
  '--ignore-rules',
  '--strict-config',
  '--ephemeral',
  '--skip-git-repo-check',
  '--config',
  'project_doc_max_bytes=0',
  '--config',
  'skills.include_instructions=false',
  '--config',
  'orchestrator.skills.enabled=false',
  '--config',
  'orchestrator.mcp.enabled=false',
  '--config',
  'suppress_unstable_features_warning=true',
  '--config',
  'default_permissions="collective"',
  '--config',
  'permissions.collective.filesystem={"/"="deny",":minimal"="read"}',
  '--config',
  'permissions.collective.network.enabled=false',
  '--config',
  'approval_policy="never"',
  '--config',
  'web_search="disabled"',
  '--config',
  'apps._default.enabled=false',
  '--config',
  'mcp_servers={}',
  ...[
    'shell_tool',
    'unified_exec',
    'shell_snapshot',
    'multi_agent',
    'apps',
    'plugins',
    'remote_plugin',
    'hooks',
    'memories',
    'external_agent_memory_import',
    'skill_search',
    'skill_mcp_dependency_install',
    'browser_use',
    'browser_use_external',
    'computer_use',
    'image_generation',
    'in_app_browser',
    'in_app_local_automation',
    'goals',
    'code_mode_host',
    'tool_suggest',
    'view_image',
  ].flatMap((feature) => ['--disable', feature]),
  '--enable',
  'skip_host_skill_discovery',
] as const;

export const COLLECTIVE_MCP_ENV_KEYS = [
  'CAT_CAFE_API_URL',
  'CAT_CAFE_INVOCATION_ID',
  'CAT_CAFE_CALLBACK_TOKEN',
  'CAT_CAFE_USER_ID',
  'CAT_CAFE_CAT_ID',
  'CAT_CAFE_THREAD_ID',
  'CAT_CAFE_MCP_PROFILE',
] as const;
