/**
 * Machine-local snapshot of the last provider-availability detection.
 *
 * Deliberately shaped like `.cat-cafe/services.json` (the existing precedent for "what is
 * installed on this machine"), and deliberately narrow:
 *
 *  - The file is **derived**. Losing it costs exactly one detection round, so it never needs a
 *    migration and is safe to delete. It is not config: nothing reads it to decide behavior.
 *  - Writes are best-effort and change-detected. A detection round must never fail because the
 *    snapshot could not be written, and an unchanged report must not rewrite the file (the
 *    report carries a fresh `detectedAt` every round, so equality is judged on a stable
 *    projection rather than the serialized report).
 *  - Mode 0600: the snapshot lists absolute install paths, which can disclose a user name.
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { resolveAccountWriteRoot } from '../../../../../config/account-store-topology.js';
import { assertSafeTestConfigRoot } from '../../../../../config/test-config-write-guard.js';
import type { ProviderAvailability, ProviderAvailabilityReport } from './provider-detection.js';

const CONFIG_SUBDIR = '.cat-cafe';
const PROVIDERS_FILENAME = 'providers.json';

/** Bumped only if the snapshot's shape changes in a way readers must branch on. */
export const PROVIDERS_SNAPSHOT_VERSION = 1;

export interface ProvidersSnapshot {
  version: number;
  note: string;
  report: ProviderAvailabilityReport;
}

export function resolveProvidersSnapshotPath(projectRoot?: string): string {
  return resolve(resolveAccountWriteRoot(projectRoot), CONFIG_SUBDIR, PROVIDERS_FILENAME);
}

/**
 * Stable fingerprint of the fields worth persisting. `detectedAt` is excluded so a routine
 * refresh with identical findings does not rewrite the file.
 */
function fingerprint(providers: readonly ProviderAvailability[]): string {
  return JSON.stringify(
    providers.map((provider) => ({
      clientId: provider.clientId,
      installed: provider.installed,
      command: provider.command,
      resolvedPath: provider.resolvedPath ?? null,
      resolvedVia: provider.resolvedVia,
      version: provider.version ?? null,
      hasApiKey: provider.hasApiKey,
      status: provider.status,
      reason: provider.reason ?? null,
      installHint: provider.installHint,
      localCli: provider.localCli,
    })),
  );
}

/** Read the snapshot, or null when absent/unreadable/from a different version. */
export function readProvidersSnapshot(projectRoot?: string): ProvidersSnapshot | null {
  const snapshotPath = resolveProvidersSnapshotPath(projectRoot);
  if (!existsSync(snapshotPath)) return null;
  try {
    const parsed = JSON.parse(readFileSync(snapshotPath, 'utf-8')) as ProvidersSnapshot;
    if (parsed?.version !== PROVIDERS_SNAPSHOT_VERSION) return null;
    if (!Array.isArray(parsed.report?.providers)) return null;
    return parsed;
  } catch {
    // A truncated or hand-edited snapshot is not an error: the next detection round replaces
    // it. Never throw here — this runs on the startup path.
    return null;
  }
}

/**
 * Persist the report, skipping the write when nothing material changed.
 *
 * Returns true when the file was (re)written. Throws only on an actual filesystem failure —
 * callers on the startup path must catch and log rather than fail the round.
 */
export function writeProvidersSnapshot(report: ProviderAvailabilityReport, projectRoot?: string): boolean {
  const root = resolveAccountWriteRoot(projectRoot);
  assertSafeTestConfigRoot(root, 'providers.writeProvidersSnapshot');

  const existing = readProvidersSnapshot(projectRoot);
  if (existing && fingerprint(existing.report.providers) === fingerprint(report.providers)) {
    return false;
  }

  const snapshotPath = resolveProvidersSnapshotPath(projectRoot);
  mkdirSync(resolve(root, CONFIG_SUBDIR), { recursive: true });
  const payload: ProvidersSnapshot = {
    version: PROVIDERS_SNAPSHOT_VERSION,
    note: 'Machine-generated by CLI provider detection. Derived, safe to delete; regenerated on the next detection round.',
    report,
  };
  const tempPath = `${snapshotPath}.tmp-${process.pid}-${Date.now()}`;
  writeFileSync(tempPath, `${JSON.stringify(payload, null, 2)}\n`, { encoding: 'utf-8', mode: 0o600 });
  try {
    renameSync(tempPath, snapshotPath);
  } catch (error) {
    try {
      unlinkSync(tempPath);
    } catch {
      /* ignore cleanup failure */
    }
    throw error;
  }
  try {
    chmodSync(snapshotPath, 0o600);
  } catch {
    // Windows / restricted filesystems may not support chmod; the write already succeeded.
  }
  return true;
}
