/**
 * Auto-generated by scripts/sop-definitions.mjs.
 * Do not edit by hand. Run: pnpm gen:sop-definitions
 */

export const SOP_DEFINITION_IDS = ['development'] as const;
export type SopDefinitionId = (typeof SOP_DEFINITION_IDS)[number];

export const DEVELOPMENT_SOP_STAGE_IDS = [
  'kickoff',
  'impl',
  'quality_gate',
  'fresh_context',
  'review',
  'merge',
  'completion',
] as const;
export type DevelopmentSopStageId = (typeof DEVELOPMENT_SOP_STAGE_IDS)[number];
export const DEVELOPMENT_SOP_DEFINITION = {
  id: 'development',
  domain: 'engineering',
  label: 'Development SOP',
  description:
    'Risk-routed development lane catalog used by WorkflowSop. Stage ids are bulletin-board lanes, not a mandatory serial pipeline; cats select only the lanes justified by behavior, data, security, contract, or irreversibility risk.\n',
  stages: [
    {
      id: 'kickoff',
      label: '立项（按需）',
      suggestedSkill: 'feat-lifecycle',
      hardRules: [
        {
          id: 'kickoff-ac-checklist',
          kind: 'hard_rule',
          text: 'Feature spec 必须有 AC + 需求点 checklist',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'feat-lifecycle' },
          predicate: {
            type: 'manual_only',
            reason:
              'Feature spec completeness is reviewed from docs and operator context; no stable machine artifact yet.',
          },
        },
      ],
      pitfalls: [
        {
          id: 'kickoff-no-unconfirmed-implementation',
          kind: 'pitfall',
          text: '没有co-creator确认就直接开始实现',
          severity: 'warn',
          owner: { type: 'stage_suggested_skill', skill: 'feat-lifecycle' },
          predicate: {
            type: 'manual_only',
            reason: 'operator confirmation is conversational intent, not yet represented as a structured event.',
          },
        },
      ],
    },
    {
      id: 'impl',
      label: '实现隔离（按需）',
      suggestedSkill: 'worktree',
      hardRules: [
        {
          id: 'impl-main-sync-before-worktree',
          kind: 'hard_rule',
          text: 'worktree 开之前必须 main 双向同步 (ahead=0 behind=0)',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'worktree' },
          predicate: {
            type: 'git_state_predicate',
            repository: 'cat-cafe',
            branch: 'main',
            checks: ['ahead_zero', 'behind_zero'],
            beforeCommand: 'git worktree add',
          },
        },
        {
          id: 'impl-redis-6398-only',
          kind: 'hard_rule',
          text: 'Redis 只用 6398，禁碰 6399',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'worktree' },
          predicate: { type: 'env_check', key: 'REDIS_URL', mustInclude: ':6398', mustNotInclude: ':6399' },
        },
        {
          id: 'impl-risk-route-before-action',
          kind: 'hard_rule',
          text: '实现前未按行为面 / 数据 / 安全 / 契约 / 不可逆五轴判断风险，就机械套用或机械跳过流程',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'worktree' },
          predicate: {
            type: 'manual_only',
            reason:
              'Risk classification is semantic; machine guards enforce concrete safety and contract boundaries after the lane is selected.',
            futureCandidate: 'risk_route_attestation',
          },
        },
        {
          id: 'impl-user-journey-missing',
          kind: 'hard_rule',
          text: '用户可感知 Feature 缺 User Journey 段（或 user_journey_exempt）',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'worktree' },
          predicate: {
            type: 'command_pattern',
            reason:
              'check-feature-truth.mjs now checks changed feature docs for ## User Journey presence. F252 root cause — session vs thread scope mismatch went undetected because journey was never written down.',
            mustMatch: 'pnpm check:features|node scripts/check-feature-truth',
          },
        },
        {
          id: 'impl-co-creation-docs-lane',
          kind: 'hard_rule',
          text: '共创型 docs-only 可自决直推；进入 worktree / PR / cloud / full gate 前才必须用 classifier 证明风险，且不得越过结果支付代码级流程税',
          severity: 'blocker',
          owner: { type: 'skill', skill: 'co-creation-docs' },
          predicate: {
            type: 'co_creation_docs_lane',
            includeGlobs: ['docs/*.md', 'docs/**/*.md'],
            classifierRequiredGlobs: [
              'docs/SOP.md',
              'docs/VISION.md',
              'docs/lessons-learned.md',
              'docs/architecture/ownership/**',
              'docs/canon/**',
              'docs/decisions/**',
            ],
            classifierMatch: 'pnpm classify:co-creation-docs|node scripts/co-creation-docs-lane.mjs',
            worktreeMatch: 'git worktree add',
            pullRequestMatch: 'gh pr create',
            cloudReviewMatch: 'gh pr comment .*@codex review',
            fullGateMatch: 'pnpm gate',
          },
        },
      ],
      pitfalls: [
        {
          id: 'impl-post-compact-recall-loss',
          kind: 'pitfall',
          text: '压缩后忘了当前在做什么',
          severity: 'warn',
          owner: { type: 'stage_suggested_skill', skill: 'worktree' },
          predicate: {
            type: 'manual_only',
            reason: 'Current runtime has no stable post-compact recall-failure telemetry.',
            futureCandidate: 'trace_pattern_post_compact_recall',
          },
        },
        {
          id: 'impl-convention-graph-before-convention-edit',
          kind: 'pitfall',
          text: '改 MCP tool / skill manifest 等当前已索引约定面前，先用 convention graph 查影响面；stale=true 先 reindex',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'worktree' },
          predicate: {
            type: 'changed_files_require_command',
            reason:
              'F242 adoption guard; convention-surface edits need a successful impact query before editing/merge.',
            mustMatch: 'pnpm convention-graph:code-consumers|cat-cafe-convention-graph code-consumers',
            includeGlobs: [
              'packages/mcp-server/src/tools/*.ts',
              'packages/mcp-server/src/server-toolsets.ts',
              'cat-cafe-skills/*/SKILL.md',
            ],
            excludeGlobs: ['**/*.test.ts', '**/*.test.js'],
          },
        },
      ],
    },
    {
      id: 'quality_gate',
      label: '自检（按风险）',
      suggestedSkill: 'quality-gate',
      hardRules: [
        {
          id: 'quality-gate-vision-coverage',
          kind: 'hard_rule',
          text: '自检报告必须包含愿景覆盖度',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'quality-gate' },
          predicate: {
            type: 'manual_only',
            reason:
              'Vision coverage has no machine-checkable report artifact yet; upgrade when quality-gate emits structured evidence.',
            futureCandidate: 'quality_gate_report_artifact',
          },
        },
      ],
      pitfalls: [
        {
          id: 'quality-gate-risk-matched-evidence',
          kind: 'pitfall',
          text: '声称完成但没有与风险面匹配的验证证据（至少 targeted；高风险才要求 full gate）',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'quality-gate' },
          predicate: {
            type: 'command_pattern',
            mustMatch: 'pnpm gate|pnpm (check|lint|test)|pnpm --filter .* test|node --test|git diff --check',
          },
        },
      ],
    },
    {
      id: 'fresh_context',
      label: 'Fresh-Context Pre-Review',
      suggestedSkill: 'fresh-context-review',
      hardRules: [],
      pitfalls: [
        {
          id: 'fresh-context-not-approval',
          kind: 'pitfall',
          text: 'Fresh-context 是 finding generator，不是 approval authority——不产出 verdict，不记入 Review Provenance Matrix',
          severity: 'warn',
          owner: { type: 'stage_suggested_skill', skill: 'fresh-context-review' },
          predicate: {
            type: 'manual_only',
            reason: 'Fresh-context output is free-form finding list, not a structured verdict event.',
          },
        },
      ],
    },
    {
      id: 'review',
      label: '独立验证（按风险择源）',
      suggestedSkill: 'request-review',
      hardRules: [
        {
          id: 'review-no-self-review',
          kind: 'hard_rule',
          text: '同一个体不能 review 自己的代码',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'request-review' },
          predicate: { type: 'handle_check', constraint: 'reviewer_not_author' },
        },
        {
          id: 'review-original-requirements',
          kind: 'hard_rule',
          text: '涉及用户意图或愿景的 Review 请求必须附原始需求摘录',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'request-review' },
          predicate: {
            type: 'manual_only',
            reason: 'Review packet content is free-form markdown; no structured requirement-excerpt field yet.',
            futureCandidate: 'review_packet_schema',
          },
        },
        {
          id: 'review-chatgpt-independent-first',
          kind: 'hard_rule',
          text: 'ChatGPT 提交代码进入专属多猫 Review round；至少两只非作者猫先独立检视，全部完成前不得互看意见',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'request-review' },
          predicate: {
            type: 'manual_only',
            reason:
              'Reviewer-private notes and the independent-review barrier are conversational state until a typed review-round carrier exists.',
            futureCandidate: 'chatgpt_review_round_barrier',
          },
        },
        {
          id: 'review-chatgpt-readonly-until-consensus',
          kind: 'hard_rule',
          text: 'ChatGPT Review 的独立检视与交叉检视阶段只读；任何猫不得 commit、push、rebase 或修改共享分支',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'request-review' },
          predicate: {
            type: 'manual_only',
            reason:
              'Git write ownership is bound to the operator-designated recorder, but review-round identity is not yet emitted as a structured Git policy event.',
            futureCandidate: 'chatgpt_review_round_git_write_guard',
          },
        },
        {
          id: 'review-chatgpt-cross-review-after-barrier',
          kind: 'hard_rule',
          text: '全部独立检视完成后才进入交叉检视；争议必须基于证据收敛，价值分歧交给co-creator',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'request-review' },
          predicate: {
            type: 'manual_only',
            reason:
              'Independent completion, note release, evidence convergence, and value escalation are semantic review-round transitions.',
            futureCandidate: 'chatgpt_review_round_state',
          },
        },
        {
          id: 'review-chatgpt-designated-recorder',
          kind: 'hard_rule',
          text: '每轮只有co-creator指定的记录猫可以将共识 ledger 提交并推送到 Git；写回成功才算本轮结束',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'request-review' },
          predicate: {
            type: 'manual_only',
            reason:
              'The Git ledger is durable truth, but recorder appointment and the successful round-close write are not yet represented by one typed receipt.',
            futureCandidate: 'chatgpt_review_round_receipt',
          },
        },
        {
          id: 'review-chatgpt-repeat-until-zero',
          kind: 'hard_rule',
          text: 'ChatGPT 按 ledger 修复后提交新 code HEAD 并开始下一轮；最新轮 open findings 非零不得合入',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'request-review' },
          predicate: {
            type: 'manual_only',
            reason:
              'Each new code HEAD requires a fresh independent and cross-review round; ledger closure is currently markdown evidence.',
            futureCandidate: 'chatgpt_review_round_open_findings_gate',
          },
        },
      ],
      pitfalls: [
        {
          id: 'review-retrigger-after-p1',
          kind: 'pitfall',
          text: 'P1/P2 修复后的实质内容未被对应 review source 覆盖；SHA-only / 可证明机械变化用 continuityProof，不重开 reviewer',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'request-review' },
          predicate: {
            type: 'manual_only',
            reason:
              'Final-SHA review coverage is the boundary; the trigger channel is lane-dependent (cloud re-trigger vs local stateful re-review). The old command_sequence predicate hardcoded the cloud incantation ("@codex review") and false-flags local-lane PRs. Truth source is merge-gate Review Provenance Matrix.',
            futureCandidate: 'review_coverage_final_sha_check',
          },
        },
      ],
    },
    {
      id: 'merge',
      label: '合入（载体触发）',
      suggestedSkill: 'merge-gate',
      hardRules: [
        {
          id: 'merge-github-squash-only',
          kind: 'hard_rule',
          text: '必须用 gh pr merge --squash（禁止本地 squash）',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'merge-gate' },
          predicate: {
            type: 'command_pattern',
            mustMatch: 'gh pr merge .*--squash',
            mustNotMatch: 'git merge --squash|git reset --soft',
          },
        },
        {
          id: 'merge-chatgpt-review-round-closed',
          kind: 'hard_rule',
          text: 'ChatGPT 仅在最新共识 ledger 为 approved_for_merge、openFindings=0 且风险门禁全绿时合入 main；合入后等待co-creator亲自验收',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'merge-gate' },
          predicate: {
            type: 'manual_only',
            reason:
              'The final ledger, reviewedCodeHead continuity proof, gate evidence, merge receipt, and post-merge operator acceptance are not yet one typed state object.',
            futureCandidate: 'chatgpt_review_round_merge_gate',
          },
        },
        {
          id: 'merge-cloud-review-sha-dedup',
          kind: 'hard_rule',
          text: '云端 review 同一 SHA 不重复触发',
          severity: 'warn',
          owner: { type: 'stage_suggested_skill', skill: 'merge-gate' },
          predicate: { type: 'sha_dedup', scope: 'cloud_review' },
        },
        {
          id: 'merge-feature-doc-truth',
          kind: 'hard_rule',
          text: 'merge 前核对 feature doc 是否说真话（Status/AC/Phase vs 代码现实），merge 后记录已合入状态',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'merge-gate' },
          predicate: {
            type: 'manual_only',
            reason:
              'Claimed-done vs code-real reconciliation is semantic; check-feature-truth mechanically guards only obvious status/timeline drift. Detailed pre/post steps live in merge-gate SKILL Step 7.5.',
            futureCandidate: 'feature_doc_truth_check',
          },
        },
        {
          id: 'merge-runtime-activation-truth',
          kind: 'hard_rule',
          text: '触及 runtime 加载面的 PR 合入后必须分开声明 main 与 live runtime 状态；未获co-creator授权时记录 live=dormant，不得冒充已生效',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'merge-gate' },
          predicate: {
            type: 'manual_only',
            reason:
              'Runtime impact, current live-load state, and operator authorization are semantic and external truths; changed filenames alone cannot prove activation.',
            futureCandidate: 'runtime_activation_receipt',
          },
        },
      ],
      pitfalls: [
        {
          id: 'merge-local-squash-close',
          kind: 'pitfall',
          text: '本地 squash + push + gh pr close（PR 显示 closed 不是 merged）',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'merge-gate' },
          predicate: { type: 'command_sequence', absent: ['gh pr merge'], antiPattern: ['git push', 'gh pr close'] },
        },
        {
          id: 'merge-runtime-update-after-merge',
          kind: 'pitfall',
          text: '合入后擅自更新 runtime',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'merge-gate' },
          predicate: {
            type: 'command_sequence',
            antiPattern: ['git pull', 'pnpm start|runtime:start|restart'],
            cwdContains: 'cat-cafe-runtime',
          },
        },
      ],
    },
    {
      id: 'completion',
      label: '愿景守护（终态触发）',
      suggestedSkill: 'feat-lifecycle',
      hardRules: [
        {
          id: 'completion-vision-guardian',
          kind: 'hard_rule',
          text: '用户可见或愿景变化的 feat close 前必须有独立愿景守护',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'feat-lifecycle' },
          predicate: {
            type: 'manual_only',
            reason: 'Guardian identity and signoff are still conversational/thread-state artifacts.',
            futureCandidate: 'guardian_signoff_event',
          },
        },
        {
          id: 'completion-pr-merged-feature-check',
          kind: 'hard_rule',
          text: 'PR merged + check:features 通过',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'feat-lifecycle' },
          predicate: { type: 'command_sequence', mustInclude: ['gh pr view', 'pnpm check:features'] },
        },
      ],
      pitfalls: [
        {
          id: 'completion-missing-guardian-handoff',
          kind: 'pitfall',
          text: '用户可见或愿景变化的 feat 没有 @ 独立守护猫就直接 close',
          severity: 'blocker',
          owner: { type: 'stage_suggested_skill', skill: 'feat-lifecycle' },
          predicate: { type: 'handle_check', constraint: 'guardian_handoff_present' },
        },
      ],
    },
  ],
  sourcePath: 'sop-definitions/development.yaml',
} as const;

export const SOP_DEFINITIONS = {
  development: DEVELOPMENT_SOP_DEFINITION,
} as const;

export type SopDefinition = (typeof SOP_DEFINITIONS)[SopDefinitionId];
export const DEFAULT_SOP_DEFINITION_ID = SOP_DEFINITION_IDS[0];
export type RuntimeSopStageId = DevelopmentSopStageId;

export type ResolvedWorkflowSopSkill = {
  readonly source: 'definition' | 'override';
  readonly skill: string;
};

export function isSopDefinitionId(value: string): value is SopDefinitionId {
  return (SOP_DEFINITION_IDS as readonly string[]).includes(value);
}

export function normalizeSopDefinitionId(value: string | null | undefined): SopDefinitionId {
  return value && isSopDefinitionId(value) ? value : DEFAULT_SOP_DEFINITION_ID;
}

export function getSopDefinition(id: string | null | undefined): SopDefinition {
  return SOP_DEFINITIONS[normalizeSopDefinitionId(id)];
}

export function resolveWorkflowSopSkill(sop: {
  readonly sopDefinitionId?: string | null;
  readonly stage: RuntimeSopStageId;
  readonly nextSkill?: string | null;
}): ResolvedWorkflowSopSkill {
  const definition = getSopDefinition(sop.sopDefinitionId);
  const stage = definition.stages.find((entry) => entry.id === sop.stage);
  if (!stage) {
    throw new Error(`Unknown SOP stage "${sop.stage}" for definition "${definition.id}"`);
  }
  if (sop.nextSkill) {
    return { source: 'override', skill: sop.nextSkill };
  }
  return { source: 'definition', skill: stage.suggestedSkill };
}
