/* eslint-disable */
// AUTO-GENERATED by scripts/gen-guide-catalog.mjs — DO NOT EDIT
// Source: guides/registry.yaml + guides/flows/*.yaml
// NOTE: This catalog uses legacy v1 step shape and is pending regeneration.
// The import below is commented out because GuideStep no longer exists in v2.

// import type { OrchestrationStep } from '@/stores/guideStore';

/** @deprecated Legacy flow shape — use OrchestrationFlow from guideStore instead. */
export interface GuideFlow {
  id: string;
  name: string;
  description: string;
  steps: LegacyGuideStep[];
}

/** @deprecated Legacy step shape kept only for catalog compat until regeneration. */
interface LegacyGuideStep {
  id: string;
  targetGuideId?: string;
  title: string;
  instruction: string;
  expectedAction: string;
  canSkip?: boolean;
  timeoutSec?: number;
}

export interface GuideRegistryEntry {
  id: string;
  name: string;
  description: string;
  keywords: string[];
  category: string;
  priority: string;
  crossSystem: boolean;
  estimatedTime: string;
}

export const GUIDE_REGISTRY: GuideRegistryEntry[] = [
  {
    id: 'add-member',
    name: '添加成员',
    description: '引导你完成新成员的创建和配置',
    keywords: ['添加成员', '加成员', '新成员', '加猫', '新猫', '新建成员', 'add member', 'add cat', 'create member'],
    category: 'member-config',
    priority: 'P0',
    crossSystem: false,
    estimatedTime: '3min',
  },
];

export const GUIDE_FLOWS: Record<string, GuideFlow> = {
  'add-member': {
    id: 'add-member',
    name: '添加成员',
    description: '引导你完成新成员的创建和配置',
    steps: [
      {
        id: 'open-hub',
        targetGuideId: 'hub.trigger',
        title: '打开 Hub',
        instruction: '点击这里打开 Hub 控制台',
        expectedAction: 'click',
      },
      {
        id: 'go-to-cats',
        targetGuideId: 'cats.overview',
        title: '进入成员总览',
        instruction: '点击「总览」查看所有成员',
        expectedAction: 'click',
      },
      {
        id: 'click-add-member',
        targetGuideId: 'cats.add-member',
        title: '添加成员',
        instruction: '点击「添加成员」开始创建',
        expectedAction: 'click',
      },
      {
        id: 'select-client',
        targetGuideId: 'add-member.client',
        title: '选择 Client',
        instruction: '选择要接入的 CLI 工具或 Agent 平台',
        expectedAction: 'select',
      },
      {
        id: 'select-provider',
        targetGuideId: 'add-member.provider-profile',
        title: '选择 Provider',
        instruction: '选择或配置 API 账号',
        expectedAction: 'select',
      },
      {
        id: 'select-model',
        targetGuideId: 'add-member.model',
        title: '选择模型',
        instruction: '选择默认使用的 AI 模型',
        expectedAction: 'select',
      },
      {
        id: 'confirm-create',
        targetGuideId: 'add-member.submit',
        title: '确认创建',
        instruction: '点击「创建后继续编辑」完成成员创建',
        expectedAction: 'click',
      },
      {
        id: 'complete',
        title: '创建完成',
        instruction: '成员创建成功！你可以继续编辑成员的详细配置。',
        expectedAction: 'confirm',
        canSkip: true,
      },
    ],
  },
};
