/**
 * F229 Phase E0 + E1: PetSkin sprite resolver.
 *
 * Pure function — conciergeState + skin → sprite info.
 * Skin-aware:
 *   - ragdoll-v1: V0 projection → 4 individual PNGs → returns URL string
 *   - yanyan-codex: V1 projection → 9-state atlas → returns atlas descriptor
 *   - yarn-ball: legacy direct ConciergeBallState → sprite path (8-state)
 *
 * No React state/effect. Manifest async loading deferred to multi-skin.
 */

import type { CodexPetState } from '@cat-cafe/shared';
import { PET_STATE_PROJECTION_V0, PET_STATE_PROJECTION_V1, projectToPetState } from '@cat-cafe/shared';

// ---------------------------------------------------------------------------
// Atlas config: yanyan-codex 9-state spritesheet
// ---------------------------------------------------------------------------

/** Single animation state row descriptor in the atlas. */
interface AtlasRowConfig {
  /** 0-based row index in the spritesheet */
  row: number;
  /** Number of frames in this animation */
  frameCount: number;
  /** Per-frame duration in ms (length === frameCount) */
  frameDurations: number[];
}

/**
 * yanyan-codex atlas layout: 8 columns × 9 rows, 192×208 cells.
 * Row order matches the spritesheet generated by 砚砚.
 */
const YANYAN_ATLAS_ROWS: Record<CodexPetState, AtlasRowConfig> = {
  idle: {
    row: 0,
    frameCount: 6,
    frameDurations: [1200, 400, 400, 500, 500, 800],
  },
  'running-right': {
    row: 1,
    frameCount: 8,
    frameDurations: [120, 120, 120, 120, 120, 120, 120, 220],
  },
  'running-left': {
    row: 2,
    frameCount: 8,
    frameDurations: [120, 120, 120, 120, 120, 120, 120, 220],
  },
  waving: {
    row: 3,
    frameCount: 4,
    frameDurations: [140, 140, 140, 280],
  },
  jumping: {
    row: 4,
    frameCount: 5,
    frameDurations: [140, 140, 140, 140, 280],
  },
  failed: {
    row: 5,
    frameCount: 8,
    frameDurations: [140, 140, 140, 140, 140, 140, 140, 240],
  },
  waiting: {
    row: 6,
    frameCount: 6,
    frameDurations: [150, 150, 150, 150, 150, 260],
  },
  running: {
    row: 7,
    frameCount: 6,
    frameDurations: [120, 120, 120, 120, 120, 220],
  },
  review: {
    row: 8,
    frameCount: 6,
    frameDurations: [150, 150, 150, 150, 150, 280],
  },
};

/** Atlas cell dimensions (pixels). */
const ATLAS_CELL_WIDTH = 192;
const ATLAS_CELL_HEIGHT = 208;

// ---------------------------------------------------------------------------
// Result types
// ---------------------------------------------------------------------------

/** Atlas-based sprite result (yanyan-codex and future atlas skins). */
export interface AtlasSpriteResult {
  kind: 'atlas';
  /** Spritesheet image URL */
  src: string;
  /** Resolved pet animation state */
  petState: CodexPetState;
  /** 0-based row index in the atlas */
  row: number;
  /** Number of frames in this animation */
  frameCount: number;
  /** Per-frame duration in ms */
  frameDurations: number[];
  /** Cell width in pixels */
  cellWidth: number;
  /** Cell height in pixels */
  cellHeight: number;
}

/** Discriminated union: either a simple URL string or an atlas descriptor. */
export type PetSpriteResult = string | AtlasSpriteResult;

// ---------------------------------------------------------------------------
// Skin base paths
// ---------------------------------------------------------------------------

/** V0 ragdoll-v1 skin base path (public static asset) */
const RAGDOLL_V1_BASE = '/concierge/skins/ragdoll-v1';

/** yanyan-codex atlas skin base path */
const YANYAN_CODEX_BASE = '/concierge/skins/yanyan-codex';

/** xianxian-codex atlas skin base path (宪宪 video-extracted 9-state atlas) */
const XIANXIAN_CODEX_BASE = '/concierge/skins/xianxian-codex';

/** Legacy yarn-ball sprite base (pre-E0 transition sprites, 8-state direct mapping) */
const YARN_BALL_BASE = '/concierge/sprites/ragdoll';

// ---------------------------------------------------------------------------
// ragdoll-v1: individual sprites (backward compat with 9-state CodexPetState)
// New states gracefully degrade to the existing 4 sprites.
// ---------------------------------------------------------------------------

const PET_STATE_SPRITES: Record<CodexPetState, string> = {
  idle: 'idle.png',
  running: 'running.png',
  'running-right': 'running.png',
  'running-left': 'running.png',
  waving: 'idle.png',
  jumping: 'idle.png',
  waiting: 'idle.png',
  review: 'review.png',
  failed: 'failed.png',
};

/** Hard-fault fallback (skin load failure / missing state) */
export const FALLBACK_SPRITE_PATH = `${RAGDOLL_V1_BASE}/idle.png`;

/**
 * Valid ConciergeBallState values that have legacy sprites.
 * Used for yarn-ball unknown-state fallback.
 */
const KNOWN_BALL_STATES = new Set([
  'idle',
  'sleeping',
  'listening',
  'thinking',
  'found',
  'needs-confirmation',
  'handoff',
  'error',
]);

/**
 * Yarn-ball legacy filename overrides.
 * Where the on-disk sprite filename differs from the ConciergeBallState string.
 * Discovered via R2 filename audit: `confirm.png` exists, `needs-confirmation.png` does not.
 */
const YARN_BALL_FILENAME_OVERRIDES: Record<string, string> = {
  'needs-confirmation': 'confirm',
};

// ---------------------------------------------------------------------------
// Resolver
// ---------------------------------------------------------------------------

/**
 * Pure function: ConciergeBallState + skin → sprite info.
 *
 * - 'ragdoll-v1' (default): V0 projection → individual PNG URL (string)
 * - 'yanyan-codex': V1 projection → atlas descriptor (AtlasSpriteResult) — 砚砚
 * - 'xianxian-codex': V1 projection → atlas descriptor (AtlasSpriteResult) — 宪宪
 * - 'yarn-ball': legacy direct mapping → sprite URL (string)
 *
 * Unknown/unmapped states fall back to idle in all paths.
 */
export function resolvePetSprite(
  ballState: string,
  skin: 'yarn-ball' | 'ragdoll-v1' | 'yanyan-codex' | 'xianxian-codex' = 'ragdoll-v1',
): PetSpriteResult {
  // -- atlas skins (yanyan-codex / xianxian-codex: same 9-state layout) --
  if (skin === 'yanyan-codex' || skin === 'xianxian-codex') {
    const base = skin === 'xianxian-codex' ? XIANXIAN_CODEX_BASE : YANYAN_CODEX_BASE;
    const petState = projectToPetState(ballState, PET_STATE_PROJECTION_V1);
    const rowConfig = YANYAN_ATLAS_ROWS[petState] ?? YANYAN_ATLAS_ROWS.idle;
    return {
      kind: 'atlas',
      src: `${base}/spritesheet.webp`,
      petState,
      row: rowConfig.row,
      frameCount: rowConfig.frameCount,
      frameDurations: [...rowConfig.frameDurations],
      cellWidth: ATLAS_CELL_WIDTH,
      cellHeight: ATLAS_CELL_HEIGHT,
    };
  }

  // -- yarn-ball legacy path --
  if (skin === 'yarn-ball') {
    const validState = KNOWN_BALL_STATES.has(ballState) ? ballState : 'idle';
    const filename = YARN_BALL_FILENAME_OVERRIDES[validState] ?? validState;
    return `${YARN_BALL_BASE}/${filename}.png`;
  }

  // -- ragdoll-v1 projection path (V0: 4-state individual sprites) --
  const petState = projectToPetState(ballState, PET_STATE_PROJECTION_V0);
  const filename = PET_STATE_SPRITES[petState] ?? PET_STATE_SPRITES.idle;
  return `${RAGDOLL_V1_BASE}/${filename}`;
}
