/**
 * Markdown → readable-text projection (F294 quote plane v2).
 *
 * The browser lets a human select characters from *rendered* Markdown, while the server
 * stores the *raw* Markdown. Those are two different character planes, so validating a
 * browser selection against raw Markdown rejects every quote that crosses a heading, bold
 * run, inline code, link or blockquote.
 *
 * **Invariant this projection must preserve**: every character sequence a reader can see
 * must appear in the projection at least as often as it appears on screen. Divergences that
 * leave *extra* text in the projection are safe — they can only produce an ambiguous or
 * absent match, and the caller fails closed. Divergences that *drop* rendered text are not:
 * they manufacture a false uniqueness, and the caller then anchors a quote onto an
 * occurrence the human never selected.
 *
 * Two design rules follow, and they are why this parses instead of pattern-matching:
 *
 * 1. **Same parser as the renderer.** An approximation of Markdown grammar has to guess
 *    whether `--` is a table delimiter, whether `| --- |` closes a real table, and what
 *    `&#128;` decodes to. Every wrong guess drops a visible occurrence. remark answers all
 *    of those exactly as the renderer does, because it *is* the renderer's parser.
 * 2. **Preserve what is not understood.** Only node types whose rendered text is known are
 *    projected from their value; anything else falls back to its raw source slice. Extra
 *    characters are the safe direction, so an unfamiliar or future construct degrades into
 *    a refused quote rather than a mis-anchored one.
 *
 * Rule 2 has a hard limit, and it is why `findGeneratedTextConstructs` exists. Some renderer
 * output has **no source counterpart at all**: a footnote reference renders a generated label
 * (`1`), and KaTeX renders glyphs that appear nowhere in `$$…$$`. No projection derived from
 * the source can carry that text, so for those constructs the occurrence-count invariant is
 * unprovable rather than merely hard. The caller must refuse to validate quotes from such a
 * message instead of anchoring against an incomplete picture.
 */
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import remarkParse from 'remark-parse';
import { unified } from 'unified';

interface MarkdownNode {
  type: string;
  value?: string;
  children?: MarkdownNode[];
  position?: { start?: { offset?: number }; end?: { offset?: number } };
}

/** Same parse configuration the chat renderer feeds ReactMarkdown. */
const parser = unified().use(remarkParse).use(remarkGfm).use(remarkMath, { singleDollarTextMath: false });

/**
 * Node types whose on-screen text is generated by the renderer rather than taken from the
 * source: footnote labels and backlinks are numbered by position, and KaTeX replaces the TeX
 * with typeset glyphs.
 */
const GENERATED_TEXT_NODES = new Set(['footnoteReference', 'footnoteDefinition', 'math', 'inlineMath']);

/** Delimiters the chat renderer normalizes into math before parsing. */
const NORMALIZED_MATH_DELIMITERS = /\\\[|\\\(/;

/** Nodes whose rendered text is exactly their value. */
const TEXT_VALUE_NODES = new Set(['text', 'inlineCode', 'code', 'math', 'inlineMath']);

/** Containers contribute no characters of their own; their children carry the text. */
const CHILD_SEPARATORS: Record<string, string> = {
  root: '\n\n',
  blockquote: '\n\n',
  list: '\n',
  listItem: '\n',
  table: '\n\n',
  tableRow: ' ',
  footnoteDefinition: '\n\n',
};
const TRANSPARENT_CONTAINERS = new Set([
  'paragraph',
  'heading',
  'emphasis',
  'strong',
  'delete',
  'link',
  'linkReference',
  'tableCell',
]);

/**
 * The projection plus, for every projected character, the source offset it was read from.
 * `null` marks characters with no single source character: separators, line breaks, and text
 * whose source spelling differs (character references). A caller that needs a source range
 * must refuse when either end of its match is `null`.
 */
export interface MarkdownReadableProjection {
  readonly text: string;
  readonly sourceOffsets: readonly (number | null)[];
}

interface Piece {
  text: string;
  offsets: (number | null)[];
}

// Offsets index UTF-16 units like every string index here; `Array.from(text)` would count code points instead.
const unitNulls = (length: number): (number | null)[] => Array.from({ length }, () => null);
const nulls = (text: string): Piece => ({ text, offsets: unitNulls(text.length) });

function sourceRange(node: MarkdownNode): { start: number; end: number } | null {
  const start = node.position?.start?.offset;
  const end = node.position?.end?.offset;
  return start === undefined || end === undefined ? null : { start, end };
}

/**
 * Aligns a text node's value with its source: equal characters map, a backslash escape maps to
 * the escaped character, container prefixes after a newline (`>`, indentation) are skipped, and a
 * character reference yields `null`. The first character that cannot be aligned ends mapping.
 */
function alignText(value: string, source: string, start: number, end: number): (number | null)[] {
  const offsets: (number | null)[] = [];
  let at = start;
  for (let index = 0; index < value.length; index += 1) {
    const character = value[index];
    if (at > start && source[at - 1] === '\n') while (at < end && /[ \t>]/.test(source[at] ?? '')) at += 1;
    // A reference is checked first: its visible character has no single source character to end a range on.
    if (
      source[at] === '&' &&
      /^&(?:#\d{1,7}|#[xX][\da-fA-F]{1,6}|[A-Za-z][A-Za-z\d]{1,31});/.test(source.slice(at, at + 40))
    ) {
      offsets.push(null);
      at = source.indexOf(';', at) + 1;
    } else if (source[at] === character) {
      offsets.push(at);
      at += 1;
    } else if (source[at] === '\\' && source[at + 1] === character) {
      offsets.push(at + 1);
      at += 2;
    } else {
      while (offsets.length < value.length) offsets.push(null);
      break;
    }
  }
  return offsets;
}

/** Code values are verbatim inside their fence or backticks; map them only where they occur exactly once. */
function alignVerbatim(value: string, source: string, start: number, end: number): (number | null)[] {
  const slice = source.slice(start, end);
  const at = slice.indexOf(value);
  if (value.length === 0 || at === -1 || slice.indexOf(value, at + 1) !== -1) return unitNulls(value.length);
  return Array.from({ length: value.length }, (_unused, index) => start + at + index);
}

function projectNode(node: MarkdownNode, source: string): Piece {
  const range = sourceRange(node);
  if (TEXT_VALUE_NODES.has(node.type)) {
    const value = node.value ?? '';
    if (!range) return nulls(value);
    const offsets =
      node.type === 'text'
        ? alignText(value, source, range.start, range.end)
        : alignVerbatim(value, source, range.start, range.end);
    return { text: value, offsets };
  }
  if (node.type === 'break') return nulls('\n');

  const separator = CHILD_SEPARATORS[node.type];
  if (separator !== undefined || TRANSPARENT_CONTAINERS.has(node.type)) {
    const joined: Piece = { text: '', offsets: [] };
    (node.children ?? []).forEach((child, index) => {
      if (index > 0 && separator) {
        joined.text += separator;
        joined.offsets.push(...nulls(separator).offsets);
      }
      const piece = projectNode(child, source);
      joined.text += piece.text;
      joined.offsets.push(...piece.offsets);
    });
    return joined;
  }

  // Unknown to this projection (raw HTML, images, thematic breaks, footnote references,
  // future syntax). Keeping the source text over-approximates what the reader sees, which
  // is the direction that fails closed.
  if (!range) return nulls('');
  return {
    text: source.slice(range.start, range.end),
    offsets: Array.from({ length: range.end - range.start }, (_unused, index) => range.start + index),
  };
}

function collectGeneratedTextNodes(node: MarkdownNode, found: Set<string>): void {
  if (GENERATED_TEXT_NODES.has(node.type)) found.add(node.type);
  for (const child of node.children ?? []) collectGeneratedTextNodes(child, found);
}

/**
 * Report the constructs in this Markdown whose rendered text cannot be derived from the
 * source. A non-empty result means the occurrence-count invariant cannot be checked, so the
 * caller must refuse to anchor a quote rather than guess.
 */
export function findGeneratedTextConstructs(markdown: string): string[] {
  const found = new Set<string>();
  collectGeneratedTextNodes(parser.parse(markdown) as MarkdownNode, found);
  if (NORMALIZED_MATH_DELIMITERS.test(markdown)) found.add('math');
  return [...found].sort();
}

/**
 * Project raw Markdown into the visible characters a Markdown renderer produces.
 * Deterministic: the result is digested and stored as evidence, so identical input must
 * always produce identical output.
 */
export function projectMarkdownReadableText(markdown: string): string {
  return projectMarkdownReadableTextWithSourceMap(markdown).text;
}

/**
 * The same projection, with the source offset behind each projected character. Both functions
 * walk one tree once, so the text here is the digested F294 projection character for character.
 */
export function projectMarkdownReadableTextWithSourceMap(markdown: string): MarkdownReadableProjection {
  const piece = projectNode(parser.parse(markdown) as MarkdownNode, markdown);
  // One offset per UTF-16 unit, or no mapping at all: a shifted map would anchor a quote on the wrong text.
  const aligned = piece.offsets.length === piece.text.length;
  return { text: piece.text, sourceOffsets: aligned ? piece.offsets : unitNulls(piece.text.length) };
}
